# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: afXzyD2viZEDI0npwSZ5SKXENMQpxUuN
            client-secret: zYq4g0lIcItSQgf9T7q3Imy2TVGx6ityZmLF-FyJj-1z4BFiiGl4Fam2WNArj6CY
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-i9d32mhe.us.auth0.com/